version: "3"

volumes:
  redis-ssl-data:

services:
  redis-ssl:
    build: "redis/"
    command: ["/app/docker-redis-entrypoint.sh"]
    container_name: redis-ssl
    ports:
      - 6379:6379
    volumes:
      - ./redis.conf:/etc/redis/redis.conf
      - redis-ssl-data:/data
      - ./:/app
